//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCcitater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrugerTable
    {
        public int BrugeID { get; set; }
        public string Navn { get; set; }
        public string BrugeNavn { get; set; }
        public string PassWord { get; set; }
    }
}
