//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCcitater.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Citater
    {
        public int CitatID { get; set; }
        [Required(ErrorMessage = "Husk Citat Overskrift.")]
        public string CitatOverskrift { get; set; }
        [Required(ErrorMessage = "Husk Citat Tekst")]
        public string CitatTekst { get; set; }
    }
}
