//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPopup
    {
        public short fldID { get; set; }
        public string fldOverskrift { get; set; }
        public string fldTeaser { get; set; }
        public string fldText { get; set; }
        public string fldImg { get; set; }
    }
}
