using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "1981a3551e10e625")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.3")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, ISEO, ISlideshow
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// baggrundsbillede: vælg et billed til baggrunden på hele siden
		///</summary>
		[ImplementPropertyType("baggrund")]
		public string Baggrund
		{
			get { return this.GetPropertyValue<string>("baggrund"); }
		}

		///<summary>
		/// baggrunds billede
		///</summary>
		[ImplementPropertyType("baggrundsBillede")]
		public string BaggrundsBillede
		{
			get { return this.GetPropertyValue<string>("baggrundsBillede"); }
		}

		///<summary>
		/// Indhold: Skiv dit hoved indhold på siden her
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}

		///<summary>
		/// Vælg et produkt der skal være i fokus: Vælg en prdukt side der skal være ekstra fokus på
		///</summary>
		[ImplementPropertyType("contentPicker")]
		public IPublishedContent ContentPicker
		{
			get { return this.GetPropertyValue<IPublishedContent>("contentPicker"); }
		}

		///<summary>
		/// Kontakt informationer og andre oplysninger.: skriv dine oplysninger som vil fremgå i footeren her og i 2 kollender.
		///</summary>
		[ImplementPropertyType("footerText")]
		public Newtonsoft.Json.Linq.JToken FooterText
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("footerText"); }
		}

		///<summary>
		/// Vælg søgeside: Vælg den side som skal vise søgeresultat
		///</summary>
		[ImplementPropertyType("searchResultPage")]
		public IPublishedContent SearchResultPage
		{
			get { return this.GetPropertyValue<IPublishedContent>("searchResultPage"); }
		}

		///<summary>
		/// Site logo: Oploud et logo her
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public string SiteLogo
		{
			get { return this.GetPropertyValue<string>("siteLogo"); }
		}

		///<summary>
		/// side navn
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		///<summary>
		/// De social medier links: tilføj eller slet sociale medier i footeren
		///</summary>
		[ImplementPropertyType("soMe")]
		public IEnumerable<IPublishedContent> SoMe
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("soMe"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Slideshow billeder
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return Umbraco.Web.PublishedContentModels.Slideshow.GetSlides(this); }
		}
	}

	// Mixin content Type 1068 with alias "sEO"
	/// <summary>SEO</summary>
	public partial interface ISEO : IPublishedContent
	{
		/// <summary>Beskrivelse af siden</summary>
		string PageDescription { get; }

		/// <summary>Sidens titel</summary>
		string PageTitle { get; }

		/// <summary>Vis/Skjul siden</summary>
		bool UmbracoNaviHide { get; }
	}

	/// <summary>SEO</summary>
	[PublishedContentModel("sEO")]
	public partial class SEO : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SEO(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SEO, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return GetPageDescription(this); }
		}

		/// <summary>Static getter for Beskrivelse af siden</summary>
		public static string GetPageDescription(ISEO that) { return that.GetPropertyValue<string>("pageDescription"); }

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return GetPageTitle(this); }
		}

		/// <summary>Static getter for Sidens titel</summary>
		public static string GetPageTitle(ISEO that) { return that.GetPropertyValue<string>("pageTitle"); }

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Vis/Skjul siden</summary>
		public static bool GetUmbracoNaviHide(ISEO that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }
	}

	/// <summary>Social Medier</summary>
	[PublishedContentModel("socialMedier")]
	public partial class SocialMedier : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "socialMedier";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialMedier(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialMedier, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Font awesome icon: Vælg en font awesom icon der passer til
		///</summary>
		[ImplementPropertyType("className")]
		public Newtonsoft.Json.Linq.JToken ClassName
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("className"); }
		}

		///<summary>
		/// Link: link til det sociale medie
		///</summary>
		[ImplementPropertyType("link")]
		public string Link
		{
			get { return this.GetPropertyValue<string>("link"); }
		}
	}

	/// <summary>Searchpage</summary>
	[PublishedContentModel("searchpage")]
	public partial class Searchpage : PublishedContentModel, ISEO, ISlideshow
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "searchpage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Searchpage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Searchpage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// billede: Vælg det billede du ønsker skal fremgå på siden
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Slideshow billeder
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return Umbraco.Web.PublishedContentModels.Slideshow.GetSlides(this); }
		}
	}

	/// <summary>Kontakt</summary>
	[PublishedContentModel("kontakt")]
	public partial class Kontakt : PublishedContentModel, ISEO, ISlideshow
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "kontakt";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Kontakt(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Kontakt, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Tekst til siden: Skriv kort om reglerne ifh. til kontakt formularen (fx. hvor lang svar tid vil der ca. være)
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}

		///<summary>
		/// Tekst under kontakt formularen: Skriv evt. lidt efter kontakt formularer
		///</summary>
		[ImplementPropertyType("tekstUnderKontaktFormularen")]
		public string TekstUnderKontaktFormularen
		{
			get { return this.GetPropertyValue<string>("tekstUnderKontaktFormularen"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Slideshow billeder
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return Umbraco.Web.PublishedContentModels.Slideshow.GetSlides(this); }
		}
	}

	// Mixin content Type 1099 with alias "slideshow"
	/// <summary>Slideshow</summary>
	public partial interface ISlideshow : IPublishedContent
	{
		/// <summary>Slideshow billeder</summary>
		IEnumerable<IPublishedContent> Slides { get; }
	}

	/// <summary>Slideshow</summary>
	[PublishedContentModel("slideshow")]
	public partial class Slideshow : PublishedContentModel, ISlideshow
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideshow";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Slideshow(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Slideshow, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Slideshow billeder
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return GetSlides(this); }
		}

		/// <summary>Static getter for Slideshow billeder</summary>
		public static IEnumerable<IPublishedContent> GetSlides(ISlideshow that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("slides"); }
	}

	/// <summary>Besked</summary>
	[PublishedContentModel("besked")]
	public partial class Besked : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "besked";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Besked(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Besked, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Beskeden
		///</summary>
		[ImplementPropertyType("msgBesked")]
		public string MsgBesked
		{
			get { return this.GetPropertyValue<string>("msgBesked"); }
		}

		///<summary>
		/// E-mail
		///</summary>
		[ImplementPropertyType("msgEmail")]
		public string MsgEmail
		{
			get { return this.GetPropertyValue<string>("msgEmail"); }
		}

		///<summary>
		/// Telefon
		///</summary>
		[ImplementPropertyType("msgTlf")]
		public string MsgTlf
		{
			get { return this.GetPropertyValue<string>("msgTlf"); }
		}
	}

	/// <summary>Overkategorier</summary>
	[PublishedContentModel("overkategorier")]
	public partial class Overkategorier : PublishedContentModel, ISEO, ISlideshow
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "overkategorier";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Overkategorier(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Overkategorier, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// information om kategorien: Skriv lidt om den overordnede kategori
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Slideshow billeder
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return Umbraco.Web.PublishedContentModels.Slideshow.GetSlides(this); }
		}
	}

	/// <summary>Kategori</summary>
	[PublishedContentModel("kategori")]
	public partial class Kategori : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "kategori";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Kategori(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Kategori, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Sidens indhold: Skriv lidt om den valgte kategori og insæt evt. billeder
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}
	}

	/// <summary>Produkt</summary>
	[PublishedContentModel("produkt")]
	public partial class Produkt : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "produkt";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Produkt(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Produkt, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Andet indhold: Der bliver lavet en overskrift med produktes navn automatisk. Så du skal IKKE lave en overskrift.
		///</summary>
		[ImplementPropertyType("bodyText")]
		public string BodyText
		{
			get { return this.GetPropertyValue<string>("bodyText"); }
		}

		///<summary>
		/// Galleri: Vælg macro og opret galleri. Skriv evt. lidt om galleriet, hvilket kamera er brugt eller andet
		///</summary>
		[ImplementPropertyType("galleri")]
		public IHtmlString Galleri
		{
			get { return this.GetPropertyValue<IHtmlString>("galleri"); }
		}

		///<summary>
		/// Antal af typen på lager: Skriv hvor mange af produktet du har på lager
		///</summary>
		[ImplementPropertyType("lagerStatus")]
		public int LagerStatus
		{
			get { return this.GetPropertyValue<int>("lagerStatus"); }
		}

		///<summary>
		/// Model type: skriv modelen
		///</summary>
		[ImplementPropertyType("modelType")]
		public string ModelType
		{
			get { return this.GetPropertyValue<string>("modelType"); }
		}

		///<summary>
		/// Produkter der ligner: Vælg produkter der ligner
		///</summary>
		[ImplementPropertyType("multiNodeTreePicker")]
		public IEnumerable<IPublishedContent> MultiNodeTreePicker
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("multiNodeTreePicker"); }
		}

		///<summary>
		/// Pris: skriv prisen, KUN TAL.
		///</summary>
		[ImplementPropertyType("price")]
		public string Price
		{
			get { return this.GetPropertyValue<string>("price"); }
		}

		///<summary>
		/// Produkt Mærke: Skriv mærket
		///</summary>
		[ImplementPropertyType("type")]
		public string Type
		{
			get { return this.GetPropertyValue<string>("type"); }
		}

		///<summary>
		/// Produktbillede: tilføj et billede at produktet
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}

		///<summary>
		/// Vejl. pris: skriv den vejlede pris KUN TAL
		///</summary>
		[ImplementPropertyType("vejlPris")]
		public string VejlPris
		{
			get { return this.GetPropertyValue<string>("vejlPris"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}
	}

	/// <summary>Informations sider</summary>
	[PublishedContentModel("informationsSider")]
	public partial class InformationsSider : PublishedContentModel, ISEO, ISlideshow
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "informationsSider";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public InformationsSider(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<InformationsSider, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hoved Indhold: ---VIGTIGT!!!--- Der bliver autogenereret en hover over skrift til siden så, så du skal IKKE lave overskrift. Skirv indholdet af siden her og indsæt billeder og evt. slideshow.
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}

		///<summary>
		/// Beskrivelse af siden: Skriv en beskrivelse af siden som giver mening når man søger på google
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageDescription(this); }
		}

		///<summary>
		/// Sidens titel: Skriv en titel på siden som giver mening i forhold til søgning på google
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Vis/Skjul siden: vis eller skjul siden
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Slideshow billeder
		///</summary>
		[ImplementPropertyType("slides")]
		public IEnumerable<IPublishedContent> Slides
		{
			get { return Umbraco.Web.PublishedContentModels.Slideshow.GetSlides(this); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Slideshow Slide</summary>
	[PublishedContentModel("slideshowSlide")]
	public partial class SlideshowSlide : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideshowSlide";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public SlideshowSlide(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlideshowSlide, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// File size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// File extension
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>Slideshow Folder</summary>
	[PublishedContentModel("slideshowImages")]
	public partial class SlideshowImages : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideshowImages";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public SlideshowImages(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlideshowImages, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
