//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartoonSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brugere
    {
        public int BrugerID { get; set; }
        public string Navn { get; set; }
        public string Brugernavn { get; set; }
        public string Password { get; set; }
    }
}
