//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartoonSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CartoonTable
    {
        public int CartoonID { get; set; }
        [Required(ErrorMessage = "Please enter Cartoon name.")]
        public string CartoonName { get; set; }
        [Required(ErrorMessage = "Please enter Cartoon Subscribe .")]
        public string CartoonsSubscribe { get; set; }
        public Nullable<int> CreatedYear { get; set; }
        [Required(ErrorMessage = "Please choose a photo .")]
        public string Photo { get; set; }
    }
}
