//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hjemmesideøvelse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TegnefilmsfigurTabel
    {
        public int TegnefilmsfigurID { get; set; }
        public string TegnefilmfigurNavn { get; set; }
        public string TegnefilmfigurBeskrivelse { get; set; }
        public System.DateTime TegnefilmfigurFoedt { get; set; }
        public string TegnefilmfigurBillede { get; set; }
    }
}
