//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP_Butik_MVC_Repetetion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int Id { get; set; }
        public string BrugerNavn { get; set; }
        public string Kodeord { get; set; }
        public string Salt { get; set; }
    }
}
