//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbProduct
    {
        public int IdProduct { get; set; }

        [Required(ErrorMessage = "Udfyld venligst")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Udfyld venligst")]
        public string AboutProduct { get; set; }

        [Required(ErrorMessage = "Udfyld venligst")]
        public int Price { get; set; }

        [Required(ErrorMessage = "Udfyld venligst")]
        public string ProductImg { get; set; }

        [Required(ErrorMessage = "Udfyld venligst")]
        public int ProcuctCategory { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
    }
}
