//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductTable
    {
        public int ProductID { get; set; }
        [Required(ErrorMessage = "Please enter Product name.")]
        public string ProductName { get; set; }
        public string ProductSubscribe { get; set; }
        [Required(ErrorMessage = "Please enter Product Price.")]
        public int Price { get; set; }
        
        public string Photo { get; set; }

        public int FK_KategoriID { get; set; }
    
        public virtual kategoriTable kategoriTable { get; set; }
    }
}
