//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontaktoplysninger
    {
        public int id { get; set; }
        public string Firmanavn { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> Postnummer { get; set; }
        public string City { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
    }
}
