//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Logins
    {
        public int Id { get; set; }
        // Tilføj Dataannotations for at lave validering på modellen
        [Required(ErrorMessage = "Udfyld venligst")]
        public string BrugerNavn { get; set; }
        public string Kodeord { get; set; }
        public string Salt { get; set; }
    }
}
