//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsSiteEntities : DbContext
    {
        public NewsSiteEntities()
            : base("name=NewsSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NyhederTable> NyhederTable { get; set; }
        public virtual DbSet<VidsteDuTable> VidsteDuTable { get; set; }
        public virtual DbSet<Kontaktoplysninger> Kontaktoplysninger { get; set; }
    }
}
