//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureTable
    {
        public int PictureID { get; set; }
        public Nullable<int> PictureProductID { get; set; }
        public string PictureFileName { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
    }
}
