//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reltest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeProductRelationTable
    {
        public int SizeProductID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
        public virtual SizeTable SizeTable { get; set; }
    }
}
