//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorProductRelationTable
    {
        public int ColorProductID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual ColorProductRelationTable ColorProductRelationTable1 { get; set; }
        public virtual ColorProductRelationTable ColorProductRelationTable2 { get; set; }
        public virtual ColorTable ColorTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
