//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opgave_REST_CRUD_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citat
    {
        public int CitatID { get; set; }
        public string Citat_Overskrift { get; set; }
        public string Citat_Tekst { get; set; }
    }
}
