//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_Skabelon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpretTable
    {
        public int ID { get; set; }
        public string Navn { get; set; }
        public string Beskrivelse { get; set; }
        public Nullable<System.DateTime> Oprettelsestidspunkt { get; set; }
        public Nullable<System.DateTime> Aarstal { get; set; }
        public string Billede { get; set; }
    }
}
