//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_Skabelon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTable()
        {
            this.ProductPhotoTable = new HashSet<ProductPhotoTable>();
        }
    
        public int ID { get; set; }
        public string Navn { get; set; }
        public string Beskrivelse { get; set; }
        public Nullable<int> Pris { get; set; }
        public Nullable<int> Antal { get; set; }
        public Nullable<int> FK_ProductCategoryID { get; set; }
    
        public virtual ProductCategoryTable ProductCategoryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhotoTable> ProductPhotoTable { get; set; }
    }
}
